// scripts/copyArtifacts.js

const fs = require('fs-extra');
const path = require('path');

async function copyArtifacts() {
  try {
    // Path to artifacts directory generated by Hardhat
    const artifactsPath = path.resolve(__dirname, '../client/artifacts');
    
    // Path to React build directory
    const buildPath = path.resolve(__dirname, '../client/build');

    // Ensure the build directory exists
    await fs.ensureDir(buildPath);

    // Copy artifacts to the build directory
    await fs.copy(artifactsPath, path.join(buildPath, 'artifacts'));
    
    console.log('Artifacts copied successfully!');
  } catch (err) {
    console.error('Error copying artifacts:', err);
  }
}

copyArtifacts();
